-- import Lean
-- import Lean.Widget.UserWidget
--
-- namespace LeanFormatterLab
--
-- open Lean Meta Elab Term
--
-- -- ===== JSON変換 =====
--
-- private def escapeJson (s : String) : String :=
  -- s.foldl (fun acc c =>
    -- acc ++ match c with
      -- | '"'  => "\\\""
      -- | '\\' => "\\\\"
      -- | '\n' => "\\n"
      -- | '\r' => "\\r"
      -- | '\t' => "\\t"
      -- | c    => String.singleton c
  -- ) ""
--
-- partial def syntaxToJson : Syntax → String
  -- | .node _ kind args =>
      -- let kids := args.toList.map syntaxToJson |>.intersperse "," |>.foldl (· ++ ·) ""
      -- s!"\{\"type\":\"node\",\"kind\":\"{escapeJson kind.toString}\",\"children\":[{kids}]}"
  -- | .atom _ val =>
      -- s!"\{\"type\":\"atom\",\"val\":\"{escapeJson val}\"}"
  -- | .ident _ _ val _ =>
      -- s!"\{\"type\":\"ident\",\"val\":\"{escapeJson val.toString}\"}"
  -- | _ =>
      -- "{\"type\":\"missing\"}"
--
-- -- ===== HTML生成 =====
--
-- def writeAnalysisHtml
    -- (termStr phase2Str phase4Str tree1Json tree3Json : String)
    -- (outPath : String := "analyze_output.html") : IO Unit := do
--
  -- let data :=
    -- "window.LEAN_DATA={" ++
    -- s!"term:\"{escapeJson termStr}\"," ++
    -- s!"phase2:\"{escapeJson phase2Str}\"," ++
    -- s!"phase4:\"{escapeJson phase4Str}\"," ++
    -- s!"tree1:{tree1Json}," ++
    -- s!"tree3:{tree3Json}" ++
    -- "};"
--
  -- let css :=
    -- ":root{--bg:#0a0a0f;--panel:#0d0d14;--bd:#1e1e2e;--tx:#cdd6f4;--dm:#585b70;--nd:#cba6f7;--at:#fab387;--id:#89dceb;--ad:#a6e3a1;--rm:#f38ba8;--ch:#f9e2af;--ac:#f5c2e7;--p1:#89b4fa;--p2:#f9e2af;--p3:#a6e3a1;--p4:#f5c2e7;--node-font:12px;--node-r:5px;}" ++
    -- "*{box-sizing:border-box;margin:0;padding:0;}" ++
    -- "html,body{width:100%;height:100%;overflow:hidden;}" ++
    -- "body{background:var(--bg);color:var(--tx);font-family:'JetBrains Mono',monospace;}" ++
--
    -- -- Header
    -- "header{height:54px;position:sticky;top:0;z-index:100;padding:.55rem 1rem;border-bottom:1px solid var(--bd);display:flex;align-items:center;gap:1rem;background:#0a0a0fee;backdrop-filter:blur(8px);}" ++
    -- "h1{font-family:'Syne',sans-serif;font-weight:800;font-size:1rem;color:var(--ac);white-space:nowrap;}" ++
    -- ".trm{font-size:.68rem;color:var(--dm);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:22vw;}" ++
    -- ".trm span{color:var(--tx);background:var(--bd);padding:.1em .4em;border-radius:3px;}" ++
--
    -- -- Controls
    -- ".ctrls{display:flex;align-items:center;gap:.55rem;font-size:.58rem;color:var(--dm);white-space:nowrap;}" ++
    -- ".ctrl{display:flex;align-items:center;gap:.25rem;}" ++
    -- ".ctrl input[type=range]{width:78px;accent-color:var(--ac);}" ++
    -- ".ctrl span{color:var(--tx);min-width:1.8rem;display:inline-block;text-align:right;}" ++
    -- ".btn{border:1px solid var(--bd);background:#12121a;color:var(--tx);border-radius:5px;padding:.18rem .45rem;font-size:.58rem;font-family:'JetBrains Mono',monospace;cursor:pointer;}" ++
    -- ".btn:hover{border-color:var(--ac);}" ++
--
    -- -- Legend
    -- ".leg{margin-left:auto;display:flex;gap:.65rem;font-size:.56rem;align-items:center;white-space:nowrap;}" ++
    -- ".li{display:flex;align-items:center;gap:.25rem;color:var(--dm);}" ++
    -- ".dot{width:6px;height:6px;border-radius:50%;}" ++
--
    -- -- Layout: Surface / Delaborated large, Expr / Pretty small
    -- ".main{display:grid;grid-template-columns:1fr 1fr;grid-template-rows:72vh 1fr;gap:1px;background:var(--bd);height:calc(100vh - 54px);overflow:hidden;}" ++
    -- ".phase{background:var(--bg);display:flex;flex-direction:column;overflow:hidden;min-width:0;min-height:0;}" ++
    -- ".ph{position:sticky;top:0;z-index:20;padding:.45rem .9rem;border-bottom:1px solid var(--bd);display:flex;align-items:center;gap:.5rem;flex-shrink:0;background:#0a0a0fee;backdrop-filter:blur(8px);}" ++
    -- ".pn{font-family:'Syne',sans-serif;font-weight:800;font-size:1.35rem;line-height:1;opacity:.18;}" ++
    -- ".pt{font-family:'Syne',sans-serif;font-weight:700;font-size:.68rem;letter-spacing:.06em;text-transform:uppercase;}" ++
    -- ".ps{font-size:.54rem;color:var(--dm);margin-left:auto;}" ++
    -- ".p1 .pn,.p1 .pt{color:var(--p1);}" ++
    -- ".p2 .pn,.p2 .pt{color:var(--p2);}" ++
    -- ".p3 .pn,.p3 .pt{color:var(--p3);}" ++
    -- ".p4 .pn,.p4 .pt{color:var(--p4);}" ++
--
    -- ".pb{flex:1;overflow:auto;position:relative;min-height:0;}" ++
    -- "svg{display:block;}" ++
    -- ".link{fill:none;stroke:var(--bd);stroke-width:1;}" ++
    -- ".node circle{stroke-width:1.5;cursor:pointer;r:var(--node-r);}" ++
    -- ".node circle:hover{opacity:.62;}" ++
    -- ".node text{font-size:var(--node-font);fill:var(--tx);pointer-events:none;font-family:'JetBrains Mono',monospace;}" ++
    -- ".nt-node circle{fill:#1a1a30;stroke:var(--nd);}" ++
    -- ".nt-atom circle{fill:#301a0a;stroke:var(--at);}" ++
    -- ".nt-ident circle{fill:#0a2530;stroke:var(--id);}" ++
    -- ".nt-missing circle{fill:#1a1a1a;stroke:var(--dm);}" ++
    -- ".nd-added circle{stroke:var(--ad)!important;stroke-width:2.8!important;}" ++
    -- ".nd-removed circle{stroke:var(--rm)!important;stroke-width:2.8!important;opacity:.35;}" ++
--
    -- ".tp{padding:1rem 1.2rem;font-size:.72rem;line-height:1.85;white-space:pre-wrap;word-break:break-all;}" ++
    -- ".po{display:flex;align-items:center;justify-content:center;height:100%;font-size:1.7rem;font-family:'Syne',sans-serif;font-weight:800;color:var(--ac);padding:1.5rem;text-align:center;white-space:pre-wrap;}" ++
--
    -- ".dov{position:absolute;right:.45rem;bottom:.45rem;background:#12121acc;border:1px solid var(--bd);border-radius:6px;padding:.28rem .42rem;font-size:.5rem;opacity:.82;z-index:30;}" ++
    -- ".ds{display:flex;align-items:center;gap:.28rem;margin-bottom:.05rem;}.ds:last-child{margin-bottom:0;}" ++
    -- ".dc{font-family:'Syne',sans-serif;font-weight:800;font-size:.6rem;min-width:.85rem;text-align:right;}" ++
--
    -- ".hint{position:absolute;left:.55rem;bottom:.55rem;background:#12121aaa;border:1px solid var(--bd);border-radius:6px;padding:.28rem .45rem;font-size:.5rem;color:var(--dm);z-index:30;}" ++
--
    -- ".tip{position:fixed;background:#12121a;border:1px solid var(--bd);border-radius:4px;padding:.35rem .65rem;font-size:.62rem;pointer-events:none;z-index:200;max-width:320px;word-break:break-all;opacity:0;transition:opacity .1s;}" ++
    -- ".tip.v{opacity:1;}" ++
    -- ".tk{color:var(--nd);font-weight:600;margin-bottom:.1rem;}" ++
    -- ".tv{color:var(--at);}" ++
--
    -- "::-webkit-scrollbar{width:4px;height:4px;}" ++
    -- "::-webkit-scrollbar-thumb{background:var(--bd);border-radius:999px;}"
--
  -- let body :=
    -- "<header><h1>Lean4 Analyzer</h1>" ++
    -- "<div class=\"trm\">term: <span id=\"td\"></span></div>" ++
--
    -- "<div class=\"ctrls\">" ++
      -- "<label class=\"ctrl\">Font <input id=\"fontCtl\" type=\"range\" min=\"8\" max=\"28\" value=\"12\"><span id=\"fontVal\">12</span></label>" ++
      -- "<label class=\"ctrl\">Node <input id=\"nodeCtl\" type=\"range\" min=\"3\" max=\"14\" value=\"5\"><span id=\"nodeVal\">5</span></label>" ++
      -- "<label class=\"ctrl\">Zoom <input id=\"zoomCtl\" type=\"range\" min=\"50\" max=\"300\" value=\"100\"><span id=\"zoomVal\">1.0</span></label>" ++
      -- "<button class=\"btn\" id=\"fitBtn\">Fit</button>" ++
      -- "<button class=\"btn\" id=\"smallBtn\">1+1</button>" ++
    -- "</div>" ++
--
    -- "<div class=\"leg\">" ++
      -- "<div class=\"li\"><div class=\"dot\" style=\"background:var(--nd)\"></div>Node</div>" ++
      -- "<div class=\"li\"><div class=\"dot\" style=\"background:var(--at)\"></div>Atom</div>" ++
      -- "<div class=\"li\"><div class=\"dot\" style=\"background:var(--id)\"></div>Ident</div>" ++
      -- "<div class=\"li\"><div class=\"dot\" style=\"background:var(--ad)\"></div>追加</div>" ++
      -- "<div class=\"li\"><div class=\"dot\" style=\"background:var(--rm)\"></div>消失</div>" ++
    -- "</div></header>" ++
--
    -- "<div class=\"main\">" ++
--
    -- -- 上段左: Surface Syntax
    -- "<div class=\"phase p1\">" ++
      -- "<div class=\"ph\"><div class=\"pn\">1</div><div class=\"pt\">Surface Syntax</div><div class=\"ps\">元の構文</div></div>" ++
      -- "<div class=\"pb\"><div id=\"t1\"></div><div class=\"hint\">Drag: pan / Wheel: zoom / Hover: detail</div></div>" ++
    -- "</div>" ++
--
    -- -- 上段右: Delaborated Syntax
    -- "<div class=\"phase p3\">" ++
      -- "<div class=\"ph\"><div class=\"pn\">3</div><div class=\"pt\">Delaborated Syntax</div><div class=\"ps\">Expr から非可逆に再構築</div></div>" ++
      -- "<div class=\"pb\"><div id=\"t3\"></div>" ++
        -- "<div class=\"dov\">" ++
          -- "<div class=\"ds\"><div class=\"dc\" style=\"color:var(--ad)\" id=\"ca\">0</div><div style=\"color:var(--dm)\">追加</div></div>" ++
          -- "<div class=\"ds\"><div class=\"dc\" style=\"color:var(--rm)\" id=\"cr\">0</div><div style=\"color:var(--dm)\">消失</div></div>" ++
        -- "</div>" ++
        -- "<div class=\"hint\">緑: Surface にない再構成ノード</div>" ++
      -- "</div>" ++
    -- "</div>" ++
--
    -- -- 下段左: Elaborated Expr
    -- "<div class=\"phase p2\">" ++
      -- "<div class=\"ph\"><div class=\"pn\">2</div><div class=\"pt\">Elaborated Expr</div><div class=\"ps\">型情報・暗黙引数・型クラス解決後</div></div>" ++
      -- "<div class=\"pb\"><div class=\"tp\" id=\"p2\"></div></div>" ++
    -- "</div>" ++
--
    -- -- 下段右: Pretty Printed Text
    -- "<div class=\"phase p4\">" ++
      -- "<div class=\"ph\"><div class=\"pn\">4</div><div class=\"pt\">Pretty Printed</div><div class=\"ps\">最終出力</div></div>" ++
      -- "<div class=\"pb\"><div class=\"po\" id=\"p4\"></div></div>" ++
    -- "</div>" ++
--
    -- "</div>" ++
    -- "<div class=\"tip\" id=\"tip\"><div class=\"tk\" id=\"tk\"></div><div class=\"tv\" id=\"tv\"></div></div>"
--
  -- let js :=
    -- "const tip=document.getElementById('tip');" ++
    -- "let treeViews=[];" ++
--
    -- "function sT(e,d){" ++
      -- "document.getElementById('tk').textContent=d.data.kind||d.data.type||'';" ++
      -- "document.getElementById('tv').textContent=d.data.val||'';" ++
      -- "tip.classList.add('v');mT(e);" ++
    -- "}" ++
    -- "function mT(e){tip.style.left=(e.clientX+14)+'px';tip.style.top=(e.clientY-8)+'px';}" ++
    -- "function hT(){tip.classList.remove('v');}" ++
--
    -- -- ノード比較用キー
    -- "function cK(n,p=''){" ++
      -- "const s=new Set();" ++
      -- "const k=p+'/'+(n.kind||n.type)+(n.val?':'+n.val:'');" ++
      -- "s.add(k);" ++
      -- "if(n.children)n.children.forEach((c,i)=>cK(c,k+'['+i+']').forEach(x=>s.add(x)));" ++
      -- "return s;" ++
    -- "}" ++
--
    -- -- Delaborated 側の追加ノードをマーク
    -- "function mD(n,k1,p=''){" ++
      -- "const k=p+'/'+(n.kind||n.type)+(n.val?':'+n.val:'');" ++
      -- "n._diff=k1.has(k)?'same':'added';" ++
      -- "if(n.children)n.children.forEach((c,i)=>mD(c,k1,k+'['+i+']'));" ++
    -- "}" ++
--
    -- -- ツリー描画
    -- "function rT(id,data,k1=null){" ++
      -- "const el=document.getElementById(id);" ++
      -- "const box=el.parentElement;" ++
      -- "const W=box.clientWidth||700;" ++
      -- "const H=box.clientHeight||500;" ++
      -- "if(k1)mD(data,k1);" ++
--
      -- "const root=d3.hierarchy(data,d=>d.children);" ++
      -- "const nc=root.descendants().length;" ++
--
      -- "const leftPad=300;" ++
      -- "const rightPad=160;" ++
      -- "const topPad=46;" ++
      -- "const bottomPad=90;" ++
--
      -- "const tH=Math.max(H+bottomPad,nc*36+topPad+bottomPad);" ++
      -- "const tW=Math.max(W+leftPad+rightPad,900);" ++
--
      -- "d3.tree().size([tH-topPad-bottomPad,tW-leftPad-rightPad])(root);" ++
--
      -- "const svg=d3.select('#'+id).append('svg').attr('width',tW).attr('height',tH);" ++
      -- "const g=svg.append('g').attr('transform','translate('+leftPad+','+topPad+')');" ++
--
      -- "const zoom=d3.zoom().scaleExtent([0.12,4]).on('zoom',e=>g.attr('transform',e.transform));" ++
      -- "svg.call(zoom);" ++
--
      -- "treeViews.push({svg:svg,g:g,zoom:zoom,leftPad:leftPad,topPad:topPad});" ++
--
      -- "g.selectAll('.link')" ++
        -- ".data(root.links())" ++
        -- ".join('path')" ++
        -- ".attr('class','link')" ++
        -- ".attr('d',d3.linkHorizontal().x(d=>d.y).y(d=>d.x));" ++
--
      -- "const node=g.selectAll('.node')" ++
        -- ".data(root.descendants())" ++
        -- ".join('g')" ++
        -- ".attr('class',d=>'node nt-'+(d.data.type||'node')+(d.data._diff&&d.data._diff!=='same'?' nd-'+d.data._diff:''))" ++
        -- ".attr('transform',d=>'translate('+d.y+','+d.x+')')" ++
        -- ".on('mouseover',sT)" ++
        -- ".on('mousemove',mT)" ++
        -- ".on('mouseout',hT);" ++
--
      -- "node.append('circle');" ++
--
      -- "node.append('text')" ++
        -- ".attr('dy','0.31em')" ++
        -- ".attr('x',d=>d.children?-10:10)" ++
        -- ".attr('text-anchor',d=>d.children?'end':'start')" ++
        -- ".text(d=>{" ++
          -- "const l=d.data.kind||d.data.val||d.data.type||'';" ++
          -- "return l.length>48?l.slice(0,46)+'…':l;" ++
        -- "});" ++
    -- "}" ++
--
    -- "const D=window.LEAN_DATA;" ++
    -- "document.getElementById('td').textContent=D.term||'';" ++
    -- "document.getElementById('p2').textContent=D.phase2||'';" ++
    -- "document.getElementById('p4').textContent=D.phase4||'';" ++
--
    -- "const k1=cK(D.tree1);" ++
    -- "rT('t1',D.tree1);" ++
    -- "rT('t3',D.tree3,k1);" ++
--
    -- -- 差分数
    -- "let added=0,removed=0;" ++
    -- "function cA(n){if(n._diff==='added')added++;if(n.children)n.children.forEach(cA);}" ++
    -- "cA(D.tree3);" ++
    -- "const k3=cK(D.tree3);" ++
    -- "k1.forEach(k=>{if(!k3.has(k))removed++;});" ++
    -- "document.getElementById('ca').textContent=added;" ++
    -- "document.getElementById('cr').textContent=removed;" ++
--
    -- -- ===== UI Controls =====
--
    -- "const fontCtl=document.getElementById('fontCtl');" ++
    -- "const nodeCtl=document.getElementById('nodeCtl');" ++
    -- "const zoomCtl=document.getElementById('zoomCtl');" ++
    -- "const fontVal=document.getElementById('fontVal');" ++
    -- "const nodeVal=document.getElementById('nodeVal');" ++
    -- "const zoomVal=document.getElementById('zoomVal');" ++
--
    -- "fontCtl.addEventListener('input',e=>{" ++
      -- "const v=e.target.value;" ++
      -- "document.documentElement.style.setProperty('--node-font',v+'px');" ++
      -- "fontVal.textContent=v;" ++
    -- "});" ++
--
    -- "nodeCtl.addEventListener('input',e=>{" ++
      -- "const v=e.target.value;" ++
      -- "document.documentElement.style.setProperty('--node-r',v+'px');" ++
      -- "nodeVal.textContent=v;" ++
    -- "});" ++
--
    -- "function applyZoom(z){" ++
      -- "zoomVal.textContent=z.toFixed(1);" ++
      -- "treeViews.forEach(v=>{" ++
        -- "const t=d3.zoomIdentity.translate(v.leftPad,v.topPad).scale(z);" ++
        -- "v.svg.call(v.zoom.transform,t);" ++
      -- "});" ++
    -- "}" ++
--
    -- "zoomCtl.addEventListener('input',e=>{" ++
      -- "const z=Number(e.target.value)/100;" ++
      -- "applyZoom(z);" ++
    -- "});" ++
--
    -- -- 標準的に見やすい設定
    -- "document.getElementById('fitBtn').addEventListener('click',()=>{" ++
      -- "fontCtl.value=16;fontCtl.dispatchEvent(new Event('input'));" ++
      -- "nodeCtl.value=8;nodeCtl.dispatchEvent(new Event('input'));" ++
      -- "zoomCtl.value=150;zoomCtl.dispatchEvent(new Event('input'));" ++
    -- "});" ++
--
    -- -- 1+1 のような小さい式用
    -- "document.getElementById('smallBtn').addEventListener('click',()=>{" ++
      -- "fontCtl.value=20;fontCtl.dispatchEvent(new Event('input'));" ++
      -- "nodeCtl.value=10;nodeCtl.dispatchEvent(new Event('input'));" ++
      -- "zoomCtl.value=210;zoomCtl.dispatchEvent(new Event('input'));" ++
    -- "});"
--
  -- let html :=
    -- "<!DOCTYPE html><html lang=\"ja\"><head><meta charset=\"UTF-8\"><title>Lean4 Analyzer</title>" ++
    -- "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js\"></script>" ++
    -- "<link href=\"https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&family=Syne:wght@700;800&display=swap\" rel=\"stylesheet\">" ++
    -- "<style>" ++ css ++ "</style></head><body>" ++
    -- body ++
    -- "<script>" ++ data ++ js ++ "</script>" ++
    -- "</body></html>"
--
  -- IO.FS.writeFile outPath html
--
-- -- ===== メインコマンド =====
--
-- elab "#analyze_term " t:term : command => do
  -- Command.liftTermElabM do
    -- let tree1Json := syntaxToJson t
    -- let termStr   := (← PrettyPrinter.ppTerm t).pretty
--
    -- let e ← elabTerm t none
    -- synthesizeSyntheticMVarsNoPostponing
    -- let e ← instantiateMVars e
    -- let phase2Str := toString e
--
    -- let delab_t ← PrettyPrinter.delab e
    -- let tree3Json := syntaxToJson delab_t
--
    -- let fmt ← PrettyPrinter.ppTerm delab_t
    -- let phase4Str := fmt.pretty
--
    -- liftM (writeAnalysisHtml termStr phase2Str phase4Str tree1Json tree3Json)
    -- logInfo m!"✓ analyze_output.html を生成しました。ブラウザで開いてください。"
--
-- end LeanFormatterLab
--
-- #analyze_term (1 + 1)